---
  networks:
    frontend:
      external: true
    backend:
      external: true
  volumes:
    prometheus-data:
      driver: local
  services:
    prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      command: "--config.file=/etc/prometheus/prometheus.yaml"
      volumes:
        - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
        - prometheus-data:/prometheus
      ports:
        - "9090:9090" 
      networks:
        - frontend
        - backend
      restart: unless-stopped
