---
networks:
  backend:
    external: true
services:
  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    command: "-config.file=/etc/promtail/promtail-config.yaml"
    volumes:
      - ./config/promtail-config.yaml:/etc/promtail/promtail-config.yaml:ro
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    ports:
      - "9080:9080"
    restart: unless-stopped
    networks:
      - backend
