name: Validate Loki

on:
  pull_request:
    branches:
      - develop
      - test
      - prod
      - main

jobs:
  validate-loki:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate Loki Config
        run: |
          docker run \
            --rm \
            -v ${{ github.workspace }}/loki/config:/config \
            grafana/loki:latest \
            -config.file=/config/loki-config.yaml \
            -verify-config=true
